### ISSUE TITLE
Where to show progressBar?

### ISSUE THREAD

**Issue by droidwithme** [eneskarpuzoglu/android-kotlin-mvvm#1]
Hello Enes,
I am learning mvvm and databinding from this repository, It is really very helpful, but I am stuck with some issues, that are
1. Where should I place a ProgressBar in this project?
2.  Where I have change the toolbar title if navigate to other fragments?
 Please help me with these confusions. Appreciated (Y)

**Comment by eneskarpuzoglu** [comment]
Dear Devendra,
I am very happy that it worked for you. You can put the progressBar on the screen during the login process for example when the login button is clicked or other requests. For the toolbar title, you can do it while designing the screens, unfortunately, there is no example in this project.

**Comment by droidwithme** [comment]
Thanks for your response, 
I understand the approach where to show the progress bar and title.
But I am not sure where to write the progressbar code in baseviewmodel or baseactivity or mainactivity. I want to write the progress bar code once and want to use same code for all application.
and for toolbar title,
I want to access toolbar (which is in main activity layout) in fragments how can I access main activity layout in various fragments?
